[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask-sqlalchemy==3.1.1",
    "flask==3.1.0",
    "flask-login==0.6.3",
]
